name: ollama

services:
  app:
    image: ollama/ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    networks:
      - ollama
    hostname: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

networks:
  ollama:
    driver: bridge
